# targets:
#   $default:
#     builders:
#       source_gen|combining_builder:
#         options:
#           ignore_for_file:
#             - implicit_dynamic_parameter
#       json_serializable:
#         options:
#           field_rename: snake
#           create_to_json: false
#           checked: true

name: open_meteo_api
description: A Dart API Client for the Open-Meteo API.
version: 1.0.0+1

environment:
  sdk: ^3.5.3
  # sdk: ">=3.6.0 <4.0.0"

dependencies:
  http: ^1.2.2
  json_annotation: ^4.9.0
  test: ^1.25.14

dev_dependencies:
  build_runner: ^2.0.0
  json_serializable: ^6.9.0
  mocktail: ^1.0.4